export const URLS = {
  LOGIN_URL: "/user/login",
  REGISTER_URL: "/user/register",
  USER_GET_URL: "/user/list",
  USER_GET_BY_ID_URL: "/user/show",
  USER_UPDATE_URL: '/user/update',
  DESTINATION_URL: "/destinations",
  SUB_DESTINATION_URL: "/sub-destinations",
  PROPERTY_CATEGORY_URL: "/categories",
  PROPERTY_TYPE_URL: "/property-types",
  ROOM_TYPE_URL: "/room-types",
  MARKET_TYPE_URL: "/market-types",
  ROOM_AMENITIES_URL: "/room-amenities",
  HOTEL_AMENITIES_URL: "/hotel-amenities",
  MEAL_PLAN_URL: "/meal-plans",
  PERMISSION_URL: "/permissions",
  USER_ROLE_URL: "/roles",
  HOTEL_URL: '/hotels',
  AGENT_URL: '/agents',
  COUNTRY_URL:'/settings/countries',
  LANGUAGE_URL:'settings/languages'
};
